name: Main
on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.12.19
    steps:
      - uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init -backend-config "bucket=jk-terraform-state-files" -backend-config "region=us-east-2" -backend-config "key=${GITHUB_REPOSITORY_SLUG}.tfstate" -backend-config "encrypt=true"
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
